# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('neighborhood', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('estate', models.CharField(max_length=30)),
                ('cep', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
