# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 22:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Oraculum_Data', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
